
spring:
  datasource:
    username: superman
    password: root123
    url: jdbc:postgresql://localhost:5432/db_book
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081
